### ISSUE TITLE
CouchDB security

### ISSUE THREAD

**Issue by dskrad** [agateblue/tempo#18]
CouchDB security is a little confusing. I have my "admin" account listed as an admin on my tempo database, but I have no "members" listed. According to CouchDB documentation, if no "members" are listed, the database is public. Therefore my tempo database is public, if someone gets my url and database name, they can see all my information. Not cool.

Now, as soon as I add a "member" to the database in CouchDB (whether that be an admin account or a regular user account), tempo webapp can no longer sync. As soon as I remove members (making my db public) it is able to sync again.

Can you check your pouchdb code and make sure that it is requiring CouchDB auth, not just for adding rows to the database, but also for retrieving rows. The current behavior makes me think that the tempo webapp is retrieving the database without sending authorization, and only uses authorization when adding rows to the database.

See [pouchdb authentication recipes](https://github.com/pouchdb-community/pouchdb-authentication/blob/master/docs/recipes.md) for more details on CouchDB security and settings for pouchdb.

**Comment by agateblue** [comment]
Hi, thank you for reporting this potential issue. There are two places in the code where we connect on a remote couchdb url through PouchDB:

1. https://github.com/agateblue/tempo/blob/main/src/store/index.js#L165-L167
2. https://github.com/agateblue/tempo/blob/main/src/store/index.js#L190-L194

We're using the [pouchdb-authentication](https://github.com/pouchdb-community/pouchdb-authentication) which provides the `logIn` method on the PouchDB database object. Once `logIn` is called, all exchanges with the remove CouchDB server are authenticated through cookies.

As far as I can tell, since we always call `logIn` before anything else, any attempt to retrieve or modify documents from the database is authenticated. 

I can also confirm I have CouchDB and Tempo synced successfully on multiple instances with authentication, working as expected.

Did you enable CORS for your Tempo domain (or any domain from which you're trying to connect to CouchDB in a browser)? I suspect it could lead to some authentication issues.

This is what I have configured on my CouchDB instance:

![image](https://user-images.githubusercontent.com/1970915/186722165-0cad1738-969b-495f-af30-8f031e94aaf7.png)

**Comment by dskrad** [comment]
I am using your hosted tempo.agate.blue domain, and yes, I have enabled CORS on my CouchDB instance.

Sync does not work when my database settings are updated to require login.

Looking at Chrome Devtools, it appears that I receive a cookie back from the "_session" request, but no cookie is sent when accessing the "tempo" database url.

Looking at your code, it would appear to require login before syncing. However, n the example from pouchdb github (the one I sent) they use the "promise, then" paradigm, while you use "await" which I am not familiar with. 

Can you check if your database is accessible via curl without auth? That's how I found out my database was not as secure as I thought. I was issuing curl requests, and even when not authorized, I was still getting back the database documents.

Can you also check your Devtools, and see if a cookie is being sent with requests to your database? If not, then there is a problem.

**Comment by dskrad** [comment]
I am syncing again!! This time securely!!

I had CORS set up, but I must have forgotten the same_site cookie attribute.

I had to set the following in CouchDB settings (local.ini):

```
[httpd]
enable_cors = true

[couch_httpd_auth]
same_site = None
```

Thanks for your patience with me.

**Comment by agateblue** [comment]
I'm glad you solved it! I'm sure the issue and solution will be helpful for other people as well ☺️
