### ISSUE TITLE
Filtering out the blueprint data ?

### ISSUE THREAD

**Issue by entropyqueen** [agateblue/tempo#50]
Hi! is there a way to filter out the blueprints data, I would like to see only the manual text entries, without having to add a tag to each of them, is this possible? :)

I tried to search for `! is:form`, but it doesn't display anything.

Also, thanks for you work, tempo is amazing :3

**Comment by agateblue** [comment]
`is:form` should display all entries associated with any blueprint form.

Is suspect the exclamation mark is the issue here. Can you try without it?

To get entries related to a specific form, you can also use the `form:form-id` filter, replacing form-id with the id from your blueprint. Another, easier way to do that is to simply click on the form title in your diary.

![Screenshot_20230121-134752](https://user-images.githubusercontent.com/1970915/213867504-43321af4-8f34-42f7-a152-0a549855b65b.png)

In this example, clicking on "injection" at the top of the diary entry gives me all the injection forms.

**Comment by agateblue** [comment]
Oh, I misunderstood. You're trying to *exclude* form entries. I don't remember if I have a `not:` operator implemented, but that could be an interesting feature.

**Comment by entropyqueen** [comment]
When I tried the filters I saw a `!` in the search, but now I think it means the important entries. I got misleaded!

**Comment by agateblue** [comment]
Through #53, you can now do `not:is:form` to achieve this result!
